### Wordpress cert ###
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: wordpress-prod
  namespace: production
  labels:
    name: wordpress-prod
spec:
  acme:
    email: johno.smakaduta@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
